nota1 = float(input("Digite a primeira nota do Aluno: \n"))
nota2 = float(input("Digite a segunda nota do Aluno: "))
nota3 = float(input("Digite a terceira nota do Aluno: "))
nota4 = float(input("Digite a ultima nota do Aluno: "))
print("A média do aluno É",(nota1 + nota2 + nota3 + nota4)/4)