Algoritmo "par e impar"


Var

Numero:inteiro

Inicio

escreval("Digite um numero")
escreval("")
leia(Numero)

se (numero MOD 2 ) = 1 entao
   escreval("seu numero é impar")
fimse

se (numero MOD 2 ) = 0 entao
   escreval("seu numero é par")
fimse

//se (numero%2) = 0 entao
    //escreva("Seu numero é par")
//fimse

//se (numero%2) = 1 entao
    //escreva("Seu numero é impar")
//fimse



Fimalgoritmo