Algoritmo "Desconto"

Var

Nome:caracter
Salario:real

Inicio

escreval("Olá, vamos calcular o desconto do INSS do seu sálario para você")
escreval("")
escreval("Primeiramente, qual seu nome?")
leia(nome)
escreval("Agora me diga o seu sálario")
leia(Salario)
escreval("Muito bem, o seu sálario com o desconto do INSS é de",Salario*0.9," Reais")
escreval("")
escreva("Muito obrigado por utilizar essa ferramenta!")
escreval("")
escreval("")

Fimalgoritmo